my/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),

]

polls/urls.py
from django.urls import path
from .views import IndexView, DetailView, vote, ResultsView
app_name='polls'
urlpatterns=[
    path('',IndexView.as_view(),name='index'),
    path('<int:pk>/',DetailView.as_view(),name='detail'),
    path('<int:question_id>/vote',vote,name='vote'),
    path('<int:pk>/results/',ResultsView.as_view(),name='results'),
    

]

polls/models.py
from datetime import  timedelta
from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('publish date')
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return timezone.now() >= self.pub_date >= timezone.now() - timedelta(days=1)
         

class Choice(models.Model):
    related_question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    vote=models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
        

polls/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        return Question.objects.filter (
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    template_name='polls/detail.html'
    model= Question
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request,question_id):
    question=get_object_or_404(Question, pk=question_id)
    try :
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request,"polls/detail.html",{'question':question,'error_message':'select and choice'})
    else:    
        selected_choice.vote += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class ResultsView(generic.DetailView):
    template_name = 'polls/results.html'
    model = Question

polls/templates/polls/detail.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<h1>{{ question.question_text }}</h1>

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token%}
    {% for choice in question.choice_set.all%}
    <input type="radio" name='choice' id='choice{{forloop.counter}}'
    value="{{choice.id}}">
    <label for='choice{{forloop.counter}}'>{{choice.choice_text}}</label>
    <br>
    {%endfor%}
    <input type="submit" value='vote'>
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for q in latest_question_list %}
        <li><a href="/polls/{{ q.id}}" >{{q.question_text}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available </p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.vote }} vote{{ choice.vote|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:index' %}">Vote again?</a>